In [1]:
pip install opendatasets --quiet --upgrade

Note: you may need to restart the kernel to use updated packages.

In [2]:
import opendatasets as od
download_url = 'https://www.kaggle.com/datasets/dansbecker/home-data-for-ml-course'

od.download(download_url)

Skipping, found downloaded files in "./home-data-for-ml-course" (use force=True to force download)

# Load the file

In [3]:
import pandas as pd

file_path = './home-data-for-ml-course/train.csv'
data = pd.read_csv(file_path)

# Understand the summary of the file 

## 1. what are the statstics metrics of the data?
## 2. How many/ what are the columns of the data?

In [4]:
data.describe()

,Id,MSSubClass,LotFrontage,LotArea,OverallQual,OverallCond,YearBuilt,YearRemodAdd,MasVnrArea,BsmtFinSF1,...,WoodDeckSF,OpenPorchSF,EnclosedPorch,3SsnPorch,ScreenPorch,PoolArea,MiscVal,MoSold,YrSold,SalePrice
count,1460.000000,1460.000000,1201.000000,1460.000000,1460.000000,1460.000000,1460.000000,1460.000000,1452.000000,1460.000000,...,1460.000000,1460.000000,1460.000000,1460.000000,1460.000000,1460.000000,1460.000000,1460.000000,1460.000000,1460.000000
mean,730.500000,56.897260,70.049958,10516.828082,6.099315,5.575342,1971.267808,1984.865753,103.685262,443.639726,...,94.244521,46.660274,21.954110,3.409589,15.060959,2.758904,43.489041,6.321918,2007.815753,180921.195890
std,421.610009,42.300571,24.284752,9981.264932,1.382997,1.112799,30.202904,20.645407,181.066207,456.098091,...,125.338794,66.256028,61.119149,29.317331,55.757415,40.177307,496.123024,2.703626,1.328095,79442.502883
min,1.000000,20.000000,21.000000,1300.000000,1.000000,1.000000,1872.000000,1950.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,2006.000000,34900.000000
25%,365.750000,20.000000,59.000000,7553.500000,5.000000,5.000000,1954.000000,1967.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,5.000000,2007.000000,129975.000000
50%,730.500000,50.000000,69.000000,9478.500000,6.000000,5.000000,1973.000000,1994.000000,0.000000,383.500000,...,0.000000,25.000000,0.000000,0.000000,0.000000,0.000000,0.000000,6.000000,2008.000000,163000.000000
75%,1095.250000,70.000000,80.000000,11601.500000,7.000000,6.000000,2000.000000,2004.000000,166.000000,712.250000,...,168.000000,68.000000,0.000000,0.000000,0.000000,0.000000,0.000000,8.000000,2009.000000,214000.000000
max,1460.000000,190.000000,313.000000,215245.000000,10.000000,9.000000,2010.000000,2010.000000,1600.000000,5644.000000,...,857.000000,547.000000,552.000000,508.000000,480.000000,738.000000,15500.000000,12.000000,2010.000000,755000.000000

In [5]:
data.columns

Index(['Id', 'MSSubClass', 'MSZoning', 'LotFrontage', 'LotArea', 'Street',
       'Alley', 'LotShape', 'LandContour', 'Utilities', 'LotConfig',
       'LandSlope', 'Neighborhood', 'Condition1', 'Condition2', 'BldgType',
       'HouseStyle', 'OverallQual', 'OverallCond', 'YearBuilt', 'YearRemodAdd',
       'RoofStyle', 'RoofMatl', 'Exterior1st', 'Exterior2nd', 'MasVnrType',
       'MasVnrArea', 'ExterQual', 'ExterCond', 'Foundation', 'BsmtQual',
       'BsmtCond', 'BsmtExposure', 'BsmtFinType1', 'BsmtFinSF1',
       'BsmtFinType2', 'BsmtFinSF2', 'BsmtUnfSF', 'TotalBsmtSF', 'Heating',
       'HeatingQC', 'CentralAir', 'Electrical', '1stFlrSF', '2ndFlrSF',
       'LowQualFinSF', 'GrLivArea', 'BsmtFullBath', 'BsmtHalfBath', 'FullBath',
       'HalfBath', 'BedroomAbvGr', 'KitchenAbvGr', 'KitchenQual',
       'TotRmsAbvGrd', 'Functional', 'Fireplaces', 'FireplaceQu', 'GarageType',
       'GarageYrBlt', 'GarageFinish', 'GarageCars', 'GarageArea', 'GarageQual',
       'GarageCond', 'PavedDrive', 'WoodDeckSF', 'OpenPorchSF',
       'EnclosedPorch', '3SsnPorch', 'ScreenPorch', 'PoolArea', 'PoolQC',
       'Fence', 'MiscFeature', 'MiscVal', 'MoSold', 'YrSold', 'SaleType',
       'SaleCondition', 'SalePrice'],
      dtype='object')

In [6]:
data.head()

,Id,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,...,PoolArea,PoolQC,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition,SalePrice
0,1,60,RL,65.0,8450,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,2,2008,WD,Normal,208500
1,2,20,RL,80.0,9600,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,5,2007,WD,Normal,181500
2,3,60,RL,68.0,11250,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,9,2008,WD,Normal,223500
3,4,70,RL,60.0,9550,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,2,2006,WD,Abnorml,140000
4,5,60,RL,84.0,14260,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,12,2008,WD,Normal,250000

# Clean out invalid data

In [7]:
data.dropna()

Empty DataFrame
Columns: [Id, MSSubClass, MSZoning, LotFrontage, LotArea, Street, Alley, LotShape, LandContour, Utilities, LotConfig, LandSlope, Neighborhood, Condition1, Condition2, BldgType, HouseStyle, OverallQual, OverallCond, YearBuilt, YearRemodAdd, RoofStyle, RoofMatl, Exterior1st, Exterior2nd, MasVnrType, MasVnrArea, ExterQual, ExterCond, Foundation, BsmtQual, BsmtCond, BsmtExposure, BsmtFinType1, BsmtFinSF1, BsmtFinType2, BsmtFinSF2, BsmtUnfSF, TotalBsmtSF, Heating, HeatingQC, CentralAir, Electrical, 1stFlrSF, 2ndFlrSF, LowQualFinSF, GrLivArea, BsmtFullBath, BsmtHalfBath, FullBath, HalfBath, BedroomAbvGr, KitchenAbvGr, KitchenQual, TotRmsAbvGrd, Functional, Fireplaces, FireplaceQu, GarageType, GarageYrBlt, GarageFinish, GarageCars, GarageArea, GarageQual, GarageCond, PavedDrive, WoodDeckSF, OpenPorchSF, EnclosedPorch, 3SsnPorch, ScreenPorch, PoolArea, PoolQC, Fence, MiscFeature, MiscVal, MoSold, YrSold, SaleType, SaleCondition, SalePrice]
Index: []

[0 rows x 81 columns]

# Specify prediction target and features (X, y)

In [8]:
y = data.SalePrice
features = ['LotArea', 'YearBuilt', '1stFlrSF', '2ndFlrSF', 'FullBath', 'BedroomAbvGr', 'TotRmsAbvGrd']
X = data[features]

# Split data into train and valid data

In [9]:
from sklearn.model_selection import train_test_split

train_X, test_X, train_y, test_y = train_test_split(X, y, test_size = 0.3)

# Specify and fit the model

## model: decision tree

In [10]:
from sklearn.tree import DecisionTreeRegressor

data_model = DecisionTreeRegressor(random_state = 1)
data_model.fit(train_X, train_y)

# Make Predictions with Validation data

In [24]:
prediction_y = data_model.predict(test_X)
print(prediction_y)

[187500.  58500. 145000. 165150. 142000. 164500. 157500. 106000. 145000.
 556581. 192000. 194201. 185750. 213250. 185000. 175500. 236000. 281213.
 180500. 143500. 202900. 140000. 153000. 129500.  81000. 151000. 116050.
 232600. 184750. 187500. 191000. 176000. 239686. 192500. 118000.  73000.
 168500. 200000.  83500. 140000. 176000. 164500. 143000. 200500. 235000.
 107400. 200500. 143900. 184900. 209500. 210000.  79500. 254000. 124500.
 173000. 122000. 191000.  87000. 197500.  83000. 197500. 133700. 274000.
 176000. 394617.  93000. 148000.  64500. 197500. 122500. 142000. 179900.
 205000. 171900.  75000. 112000. 209500. 164500.  90000. 132500. 144000.
  97000. 239799. 192500. 114500. 191000. 191000. 108500. 156000. 230000.
 180500. 106500.  79900. 172500. 239900. 348000. 185750. 175500. 212900.
 252000. 385000. 190000. 150000. 180500. 165150. 155835. 259000. 147000.
 134000. 142500. 181500. 179200. 281000. 278000. 142500. 119000. 118500.
 263000. 311500. 100000. 556581. 240000. 140000. 160000. 325000. 132500.
  91000. 191000. 132500. 153337. 119750. 211000. 171000. 194500. 106500.
 164500. 157000. 255900. 252000. 168500. 150000. 127000. 135000. 173500.
 181000. 194000. 134500. 179665. 252000. 195000. 207500. 148000. 157500.
 108500. 122000. 133900. 118500. 240000. 133900. 180500. 110000. 174500.
 214000. 175000.  93200. 184900.  89500. 149000. 194201. 109500. 253293.
 145500. 129000. 142500. 280000. 109500.  82500. 155000. 132500. 133900.
 325000. 120000. 225000. 133900. 120000. 190000. 156000. 242000. 159434.
 100000. 342643. 240000. 195000. 132000. 133000. 190000. 556581. 145000.
 190000. 112000. 118500. 134500. 218000. 205000. 275500. 163000. 272000.
  82000. 112000. 191000. 132500. 105000. 121500. 143000. 124500. 118500.
 149000. 120000. 133700. 124500. 191000. 191000. 162000. 118400. 115000.
 180500. 180500. 127000. 440000. 180500. 162000. 124500. 124500. 128000.
 192000.  97500. 377426. 210000. 149000. 169500. 193500. 157000. 133700.
  75000. 232000. 244400. 180500. 246578. 186500. 145000. 185000. 188000.
 274300. 268000. 280000. 183000. 253293. 137500. 178000. 159500. 255000.
 219500. 106250. 222000. 241500. 274900. 385000. 385000. 101800. 255900.
 109008. 227000. 118500. 186500. 290000. 274900. 219500. 180500.  82500.
 175500. 280000. 230000.  79900. 124000. 556581. 207500. 173000. 148000.
 205000. 135000. 148000. 106500. 202900. 178400. 132500. 171000. 284000.
 240000. 162900. 244000. 311500. 164500. 105000. 392000. 101800. 133900.
 165000. 112000.  99500. 107400. 148000. 267000. 162900. 194500. 224900.
 342643. 190000. 139000. 186500. 129000. 251000. 312500. 176485. 145000.
 163000. 185000. 230000. 284000. 377500. 107400. 106500. 212000. 100000.
 143000. 171000. 205000. 205000. 148000. 395192.  85500. 130000. 141000.
 213000. 194500. 182000. 175000. 395192. 136500. 125500. 194201. 184900.
 140000. 154000. 150000. 215000. 124000. 333168. 236000. 211000. 200500.
 161000.  96500. 110000. 152000. 180500. 125500. 139400. 197500. 174500.
 122000. 106000. 178900. 130000. 145150. 119200. 163000. 185850. 103200.
 230000. 180500. 203000. 139950. 260000. 100000. 252000. 157000. 127000.
 129000. 101000. 137500. 115000. 117500. 156000. 245350. 187000. 145000.
 100000. 556581. 333168.  58500. 131500. 135000. 202665. 164500. 122000.
 325000. 190000. 372500. 134000. 232000. 135000. 200500. 179665. 279500.
 254000. 115000. 180000. 256300. 140000. 125500. 150000. 179000. 194201.
 212000. 109008. 185000. 180500. 138000. 190000. 465000. 194201. 148800.
 129000. 167900. 139400. 118500. 325000. 155000.]

# Calculate the Mean Absolute Error in Validation Data

In [13]:
from sklearn.metrics import mean_absolute_error

mae = mean_absolute_error(prediction_y, test_y)
print(mae)

28483.837899543378

# Find the optimal tree leaves based on lowest MAE

In [31]:
def get_mae(max_leaf_nodes, train_X, test_X, train_y, test_y):
    
    data_model = DecisionTreeRegressor(max_leaf_nodes = max_leaf_nodes, random_state = 0)
    data_model.fit(train_X, train_y)
    prediction_y = data_model.predict(test_X)
    mae = mean_absolute_error(test_y, prediction_y)
    
    return mae

leaves = [5, 25, 50, 100, 250, 500]
score = {i: get_mae(i, train_X, test_X, train_y, test_y) for i in leaves}
best_leaf = min(score, key = score.get)

final_model = DecisionTreeRegressor(max_leaf_nodes = best_leaf, random_state=0)